/**
 * Constructs login payload from form data and CAPTCHA token.
 * @param formData Form data containing email and password
 * @param captchaToken Token generated by CAPTCHA service
 * @returns Login payload with normalized email and credentials
 */
import type { LoginPayload } from '../interfaces/LoginPayload';

export const buildLoginPayload = (
  formData: FormData,
  captchaToken: string,
): LoginPayload => {
  return {
    email: String(formData.get('email') ?? '').trim().toLowerCase(),
    password: String(formData.get('password') ?? ''),
    captcha_token: captchaToken,
  };
};